version: "3.8"

services:
  parking_app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: parking_interface
    env_file:
      - .env
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
      - ../collab-services/Camera-service/data/events:/var/www/html/public/events:z
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux: resolve host from container
    networks:
      - parking_net
    restart: unless-stopped


  adminer:
    image: adminer:4
    container_name: parking_adminer
    ports:
      - "8082:8080"          # http://localhost:8081
    environment:
      ADMINER_DEFAULT_SERVER: host.docker.internal  # your host Postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - parking_net
    restart: unless-stopped


  parking_web:
    image: nginx:1.25-alpine
    container_name: parking_web
    ports:
      - "8083:80"
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage:ro
      - ./bootstrap/cache:/var/www/html/bootstrap/cache:ro
      - ../collab-services/Camera-service/data/events:/var/www/html/public/events:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - parking_app                       # only web depends on app
    networks:
      - parking_net
    restart: unless-stopped

networks:
  parking_net:
    driver: bridge
